app = 'tasker-cold-butterfly-7622'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.23.4'

[http_service]
  internal_port = 42069
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
