package main

import (
	"embed"
	"fmt"

	app "btct/app"
	server "btct/server"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

// Embed the `dist` directory generated by Vite
//
//go:embed dist/*
var staticFiles embed.FS

const PORT = "42069"

func main() {
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	// Serve static files from the embedded `dist` directory
	e.StaticFS("/", echo.MustSubFS(staticFiles, "dist"))
	appInstance := app.NewApp()

	// api routes
	api := e.Group("/api")
	api.GET("/", server.FuncTaskIndex())
	api.GET("/task/:id", server.FuncTaskId(appInstance))
	api.POST("/tasks/create", server.FuncTaskAdd(appInstance))
	api.PUT("/tasks/:id/complete", server.FuncTaskMarkComplete(appInstance))
	api.POST("/nfc", server.FuncTaskFromNFC(appInstance))

	// start app
	e.Logger.Fatal(e.Start(fmt.Sprintf(":%s", PORT)))

}
