package main

import (
	"database/sql"
	"embed"
	"log"

	app "btct/app"
	server "btct/server"

	_ "github.com/mattn/go-sqlite3"
)

// Embed the `dist` directory generated by Vite
//
//go:embed dist/*
var staticFiles embed.FS

//go:embed schema.sql
var ddl string

const DB_FILE = "btct.db"

func main() {
	// Connect to the SQLite database

	db, err := sql.Open("sqlite3", DB_FILE)
	if err != nil {
		log.Fatalf("Failed to connect to SQLite: %v", err)
	}

	defer db.Close()

	appInstance := app.NewApp(db)
	err = appInstance.Init(ddl)
	if err != nil {
		log.Fatalf("An error occured initializing database: %w", err)
	}
	server.StartServer(appInstance, staticFiles)
}
