	CREATE TABLE IF NOT EXISTS tasks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		description TEXT NOT NULL,
		complete BOOLEAN NOT NULL DEFAULT 0
	);

	CREATE TABLE IF NOT EXISTS migrations (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
    count INTEGER,
		description TEXT NOT NULL
  );
