// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Migration struct {
	ID          int64
	Count       sql.NullInt64
	Description string
}

type Task struct {
	ID          int64
	Description string
	Complete    bool
}
